### ISSUE TITLE
Error when using custom font

### ISSUE THREAD

**Issue by Wildhoney** [yuanbohan/rs-figlet#12]
When I try to use [univers](http://www.figlet.org/fonts/univers.flf) I get:

> `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "one line len can't be less than 2. it is:@"', src/renderer/mod.rs:23:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

(`small` from the example in the repo works just fine)

**Comment by swz-git** [comment]
also having this issue

**Comment by Wildhoney** [comment]
Seems to work perfectly well [without the check](https://github.com/yuanbohan/rs-figlet/pull/13).

**Comment by yuanbohan** [comment]
> Seems to work perfectly well [without the check](https://github.com/yuanbohan/rs-figlet/pull/13).

Thanks a lot，sorry for the delay with limited time

**Comment by Wildhoney** [comment]
np at all. I’m in exactly the same position 👍
