### ISSUE TITLE
Does not display the banner

### ISSUE THREAD

**Issue by upgundecha** [yuanbohan/rs-figlet#7]
Hi @yuanbohan,

I'm using this lib in my program as below. But it does not display the banner when I run the program.
How do we display the banner?
```
use figlet_rs::FIGfont;

fn main() {
    let small_font = FIGfont::from_file("resources/small.flf").unwrap();
    let figure = small_font.convert("HELLO");
    assert!(figure.is_some());
}

```
Thanks,
Unmesh

**Comment by yuanbohan** [comment]
hi @upgundecha , just unwrap it and print will be ok, I will update the readme. sorry about the confusion

```
println!("{}", figure.unwrap());
```
